##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

  #[create-unique-path--]
variables:
# Use the umdev LLNL service user to run CI. This prevents from running
# pipelines as an actual user.
  LLNL_SERVICE_USER: bradiuss

# Use the service user workspace. Solves permission issues, stores everything
# at the same location whoever triggers a pipeline.
  CUSTOM_CI_BUILDS_DIR: /usr/workspace/bradiuss/gitlab-runner

  MY_SPACK_PARENT_DIR: ${CUSTOM_CI_BUILDS_DIR}/llnl-stack-${CI_PIPELINE_ID}
  MY_SPACK_PATH: ${CUSTOM_CI_BUILDS_DIR}/llnl-stack-${CI_PIPELINE_ID}/spack
  MY_SPACK_USER_CACHE: /dev/shm/llnl-stack-${CI_PIPELINE_ID}-${CI_JOB_ID}/spack-cache
  #[--create-unique-path]
  MY_SPACK_DEBUG: ""
  MY_ENV_NAME: "none"

# We only do one generation per stage because we found conflicts otherwise
#[one-generate-per-stage--]
stages:
  - setup
  - generate
  - build
  - clean
#[--one-generate-per-stage]

# Run a simple jobs to display instructions when no env name was specified.
no-env-name:
  extends: [.on-quartz]
  rules:
    - if: '$MY_ENV_NAME == "none"'
      when: always
    - when: never
  stage: setup
  script:
    - echo "Variable \"MY_ENV_NAME\" was not set."
    - echo "\"MY_ENV_NAME\" is required and should point to an existing directory in spack-environments."
    - exit 1

.env_defined:
  rules:
    - if: '$MY_ENV_NAME == "none"'
      when: never
    - if: '$CI_JOB_NAME =~ /rm-spack/'
      when: always
    - when: on_success

.on-quartz:
  tags: [shell, quartz]

.on-lassen:
  tags: [shell, lassen]

include:
  - local: .gitlab/generate.yml
    rules:
      - if: '$MY_ENV_NAME != "none"'
