##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

  #[create-unique-path--]
variables:
  SPACK_PARENT_DIR: ${CI_BUILDS_DIR}/../../llnl-stack-${CI_COMMIT_SHORT_SHA}
  SPACK_PATH: ${CI_BUILDS_DIR}/../../llnl-stack-${CI_COMMIT_SHORT_SHA}/spack
  #[--create-unique-path]
  SPACK_DEBUG: "-d"
  ENV_NAME: "raja-suite"
  SPACK_REPO: https://github.com/spack/spack.git
  SPACK_REF: develop

# We only do one generation per stage because we found conflicts otherwise
#[one-generate-per-stage--]
stages:
  - setup
  - generate-quartz
  - generate-lassen
  - build
  - clean
#[--one-generate-per-stage]

.on-quartz:
  tags: [shell, quartz]

.on-lassen:
  tags: [shell, lassen]

include:
  - local: .gitlab/generate.yml
  - local: spack-environments/radiuss/ci-variables.yml
    rules:
      - if: '$ENV_NAME == "radiuss"'
  - local: spack-environments/raja-suite/ci-variables.yml
    rules:
      - if: '$ENV_NAME == "raja-suite"'
