##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

  #[create-unique-path--]
variables:
# Use the umdev LLNL service user to run CI. This prevents from running
# pipelines as an actual user.
  LLNL_SERVICE_USER: bradiuss

# Use the service user workspace. Solves permission issues, stores everything
# at the same location whoever triggers a pipeline.
  CUSTOM_CI_BUILDS_DIR: /usr/workspace/bradiuss/gitlab-runner

  SPACK_PARENT_DIR: ${CI_BUILDS_DIR}/../../llnl-stack-${CI_PIPELINE_ID}
  SPACK_PATH: ${CI_BUILDS_DIR}/../../llnl-stack-${CI_PIPELINE_ID}/spack
  #[--create-unique-path]
  SPACK_DEBUG: "-d"
  ENV_NAME: ""

# We only do one generation per stage because we found conflicts otherwise
#[one-generate-per-stage--]
stages:
  - setup
  - generate-quartz
  - generate-lassen
  - build
  - clean
#[--one-generate-per-stage]

.on-quartz:
  tags: [shell, quartz]

.on-lassen:
  tags: [shell, lassen]

include:
  - local: .gitlab/generate.yml
