##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  MY_SPACK_REPO: https://github.com/spack/spack.git
  MY_SPACK_BRANCH: llnl/radiuss-packages-update

include:
  - local: .gitlab/ruby.yml
  - local: .gitlab/lassen.yml
