##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  MY_SPACK_REPO: https://github.com/spack/spack.git
  #MY_SPACK_COMMIT: 2d464f8c8903ce57cabe411bbe979583d4ccdb5d # develop-2024-06-16
  MY_SPACK_COMMIT: aeaa922eef45b14199b486fa2c188252df8c9544 # develop-2024-07-07

include:
  - local: .gitlab/ruby.yml
  - local: .gitlab/lassen.yml
