##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  MY_SPACK_REPO: https://github.com/spack/spack.git
  MY_SPACK_COMMIT: 2d464f8c8903ce57cabe411bbe979583d4ccdb5d

include:
  - local: .gitlab/ruby.yml
  - local: .gitlab/lassen.yml
