##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  MY_SPACK_REPO: https://github.com/spack/spack.git
  MY_SPACK_COMMIT: 8564ab19c324ca634f6dd50bdb5413a645179ef1

include:
  - local: .gitlab/ruby.yml
  - local: .gitlab/lassen.yml
