##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  MY_SPACK_REPO: https://github.com/davidbeckingsale/spack.git
  MY_SPACK_COMMIT: c2af154cd24ab3ef501a7efc020f818ef60aa552

include:
  - local: .gitlab/quartz.yml
  - local: .gitlab/lassen.yml
